// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id         int64       `orm:"id,primary"      json:"id"`         //
	Number     string      `orm:"number,unique"   json:"number"`     // 学号
	Name       string      `orm:"name"            json:"name"`       // 用户姓名
	Username   string      `orm:"username,unique" json:"username"`   // 用户名称
	Password   string      `orm:"password"        json:"password"`   // 用户密码
	Gender     string      `orm:"gender"          json:"gender"`     // 男｜女｜未公开
	CreateTime *gtime.Time `orm:"create_time"     json:"createTime"` //
	UpdateTime *gtime.Time `orm:"update_time"     json:"updateTime"` //
}
