// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package dao

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/gmvc"
)

// UserDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type UserDao struct {
	gmvc.M              // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB      // DB is the raw underlying database management object.
	Table   string      // Table is the table name of the DAO.
	Columns UserColumns // Columns contains all the columns of Table that for convenient usage.
}

// UserColumns defines and stores column names for table user.
type UserColumns struct {
	Id         string //
	Number     string // 学号
	Name       string // 用户姓名
	Username   string // 用户名称
	Password   string // 用户密码
	Gender     string // 男｜女｜未公开
	CreateTime string //
	UpdateTime string //
}

/*var (
	// User is globally public accessible object for table user operations.
	User = UserDao{
		M:     g.DB("default").Model("user").Safe(),
		DB:    g.DB("default"),
		Table: "user",
		Columns: userColumns{
			Id:         "id",
			Number:     "number",
			Name:       "name",
			Username:   "username",
			Password:   "password",
			Gender:     "gender",
			CreateTime: "create_time",
			UpdateTime: "update_time",
		},
	}
)*/
