// Code generated by goctl. DO NOT EDIT.
package types

type UserOneReq struct {
	Id int64 `json:"id" v:"min:4"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginRes struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Gender      string `json:"gender"`
	Number      string `json:"number"`
	Username    string `json:"username"`
	AccessToken string `json:"accessToken"`
}
